version: '3.8'
services:
  app:
    dns:
      - 114.114.114.114
      - 223.5.5.5
    container_name: app_container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"  # 外部 8080 -> 容器 8080 (可选, 仅调试用)
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=DECpassword
      - DB_NAME=backend_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
      - frontend
    restart: on-failure

  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: DECpassword
      MYSQL_DATABASE: backend_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 新增的 Nginx 服务
  nginx:
    container_name: nginx_container
    image: nginx:latest
    depends_on:
      - app
    networks:
      - frontend
    # 不再暴露 80/443 到宿主机，因为 Caddy 对外提供
    # 如果你想本地调试 Nginx，可加端口映射:
    # ports:
    #   - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  caddy:
    container_name: caddy_container
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - nginx
    networks:
      - frontend
    restart: unless-stopped

volumes:
  db_data:
  caddy_data:
  caddy_config:

networks:
  backend:
  frontend: