version: '3.8'
services:
  app:
    dns:
      - 114.114.114.114
      - 223.5.5.5
    container_name: app_container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      # 改为 "8080:8080"，让外部访问 8080 => 容器内部 8080
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=DECpassword
      - DB_NAME=backend_db
      # - GODEBUG=http2client=0
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
      - frontend
    restart: on-failure

  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: DECpassword
      MYSQL_DATABASE: backend_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    container_name: nginx_container
    image: nginx:latest
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - frontend

volumes:
  db_data:

networks:
  backend:
  frontend: